// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ALexfonSchneider/goplatform/pkg/platform/mocks (interfaces: NamedComponent,HealthCheckComponent)
//
// Generated by this command:
//
//	mockgen -destination=pkg/platform/mocks/mock_composites.go -package=mocks github.com/ALexfonSchneider/goplatform/pkg/platform/mocks NamedComponent,HealthCheckComponent
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockNamedComponent is a mock of NamedComponent interface.
type MockNamedComponent struct {
	ctrl     *gomock.Controller
	recorder *MockNamedComponentMockRecorder
	isgomock struct{}
}

// MockNamedComponentMockRecorder is the mock recorder for MockNamedComponent.
type MockNamedComponentMockRecorder struct {
	mock *MockNamedComponent
}

// NewMockNamedComponent creates a new mock instance.
func NewMockNamedComponent(ctrl *gomock.Controller) *MockNamedComponent {
	mock := &MockNamedComponent{ctrl: ctrl}
	mock.recorder = &MockNamedComponentMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNamedComponent) EXPECT() *MockNamedComponentMockRecorder {
	return m.recorder
}

// Name mocks base method.
func (m *MockNamedComponent) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockNamedComponentMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockNamedComponent)(nil).Name))
}

// Start mocks base method.
func (m *MockNamedComponent) Start(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockNamedComponentMockRecorder) Start(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockNamedComponent)(nil).Start), ctx)
}

// Stop mocks base method.
func (m *MockNamedComponent) Stop(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockNamedComponentMockRecorder) Stop(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockNamedComponent)(nil).Stop), ctx)
}

// MockHealthCheckComponent is a mock of HealthCheckComponent interface.
type MockHealthCheckComponent struct {
	ctrl     *gomock.Controller
	recorder *MockHealthCheckComponentMockRecorder
	isgomock struct{}
}

// MockHealthCheckComponentMockRecorder is the mock recorder for MockHealthCheckComponent.
type MockHealthCheckComponentMockRecorder struct {
	mock *MockHealthCheckComponent
}

// NewMockHealthCheckComponent creates a new mock instance.
func NewMockHealthCheckComponent(ctrl *gomock.Controller) *MockHealthCheckComponent {
	mock := &MockHealthCheckComponent{ctrl: ctrl}
	mock.recorder = &MockHealthCheckComponentMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHealthCheckComponent) EXPECT() *MockHealthCheckComponentMockRecorder {
	return m.recorder
}

// HealthCheck mocks base method.
func (m *MockHealthCheckComponent) HealthCheck(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HealthCheck", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// HealthCheck indicates an expected call of HealthCheck.
func (mr *MockHealthCheckComponentMockRecorder) HealthCheck(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HealthCheck", reflect.TypeOf((*MockHealthCheckComponent)(nil).HealthCheck), ctx)
}

// Start mocks base method.
func (m *MockHealthCheckComponent) Start(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockHealthCheckComponentMockRecorder) Start(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockHealthCheckComponent)(nil).Start), ctx)
}

// Stop mocks base method.
func (m *MockHealthCheckComponent) Stop(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockHealthCheckComponentMockRecorder) Stop(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockHealthCheckComponent)(nil).Stop), ctx)
}
