// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ALexfonSchneider/goplatform/pkg/platform (interfaces: Plugin,PluginContext)
//
// Generated by this command:
//
//	mockgen -destination=pkg/platform/mocks/mock_plugin.go -package=mocks github.com/ALexfonSchneider/goplatform/pkg/platform Plugin,PluginContext
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	platform "github.com/ALexfonSchneider/goplatform/pkg/platform"
	gomock "go.uber.org/mock/gomock"
)

// MockPlugin is a mock of Plugin interface.
type MockPlugin struct {
	ctrl     *gomock.Controller
	recorder *MockPluginMockRecorder
	isgomock struct{}
}

// MockPluginMockRecorder is the mock recorder for MockPlugin.
type MockPluginMockRecorder struct {
	mock *MockPlugin
}

// NewMockPlugin creates a new mock instance.
func NewMockPlugin(ctrl *gomock.Controller) *MockPlugin {
	mock := &MockPlugin{ctrl: ctrl}
	mock.recorder = &MockPluginMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPlugin) EXPECT() *MockPluginMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockPlugin) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockPluginMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockPlugin)(nil).Close))
}

// Init mocks base method.
func (m *MockPlugin) Init(reg platform.PluginContext) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Init", reg)
	ret0, _ := ret[0].(error)
	return ret0
}

// Init indicates an expected call of Init.
func (mr *MockPluginMockRecorder) Init(reg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Init", reflect.TypeOf((*MockPlugin)(nil).Init), reg)
}

// Name mocks base method.
func (m *MockPlugin) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockPluginMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockPlugin)(nil).Name))
}

// MockPluginContext is a mock of PluginContext interface.
type MockPluginContext struct {
	ctrl     *gomock.Controller
	recorder *MockPluginContextMockRecorder
	isgomock struct{}
}

// MockPluginContextMockRecorder is the mock recorder for MockPluginContext.
type MockPluginContextMockRecorder struct {
	mock *MockPluginContext
}

// NewMockPluginContext creates a new mock instance.
func NewMockPluginContext(ctrl *gomock.Controller) *MockPluginContext {
	mock := &MockPluginContext{ctrl: ctrl}
	mock.recorder = &MockPluginContextMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPluginContext) EXPECT() *MockPluginContextMockRecorder {
	return m.recorder
}

// Component mocks base method.
func (m *MockPluginContext) Component(name string) (platform.Component, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Component", name)
	ret0, _ := ret[0].(platform.Component)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Component indicates an expected call of Component.
func (mr *MockPluginContextMockRecorder) Component(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Component", reflect.TypeOf((*MockPluginContext)(nil).Component), name)
}

// Logger mocks base method.
func (m *MockPluginContext) Logger() platform.Logger {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logger")
	ret0, _ := ret[0].(platform.Logger)
	return ret0
}

// Logger indicates an expected call of Logger.
func (mr *MockPluginContextMockRecorder) Logger() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logger", reflect.TypeOf((*MockPluginContext)(nil).Logger))
}

// OnAfterStart mocks base method.
func (m *MockPluginContext) OnAfterStart(h platform.AfterStartHook) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnAfterStart", h)
}

// OnAfterStart indicates an expected call of OnAfterStart.
func (mr *MockPluginContextMockRecorder) OnAfterStart(h any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnAfterStart", reflect.TypeOf((*MockPluginContext)(nil).OnAfterStart), h)
}

// OnAfterStop mocks base method.
func (m *MockPluginContext) OnAfterStop(h platform.AfterStopHook) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnAfterStop", h)
}

// OnAfterStop indicates an expected call of OnAfterStop.
func (mr *MockPluginContextMockRecorder) OnAfterStop(h any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnAfterStop", reflect.TypeOf((*MockPluginContext)(nil).OnAfterStop), h)
}

// OnBeforeStart mocks base method.
func (m *MockPluginContext) OnBeforeStart(h platform.BeforeStartHook) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnBeforeStart", h)
}

// OnBeforeStart indicates an expected call of OnBeforeStart.
func (mr *MockPluginContextMockRecorder) OnBeforeStart(h any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnBeforeStart", reflect.TypeOf((*MockPluginContext)(nil).OnBeforeStart), h)
}

// OnBeforeStop mocks base method.
func (m *MockPluginContext) OnBeforeStop(h platform.BeforeStopHook) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnBeforeStop", h)
}

// OnBeforeStop indicates an expected call of OnBeforeStop.
func (mr *MockPluginContextMockRecorder) OnBeforeStop(h any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnBeforeStop", reflect.TypeOf((*MockPluginContext)(nil).OnBeforeStop), h)
}

// Register mocks base method.
func (m *MockPluginContext) Register(name string, c platform.Component) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", name, c)
	ret0, _ := ret[0].(error)
	return ret0
}

// Register indicates an expected call of Register.
func (mr *MockPluginContextMockRecorder) Register(name, c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockPluginContext)(nil).Register), name, c)
}
